#!/bin/bash

sudo ip netns add netns0
sudo ip link add veth0 type veth peer name veth1
sudo ip link set veth1 netns netns0
sudo ip link set veth0 up
sudo ip addr add 10.0.0.1/24 dev veth0
sudo ip netns exec netns0 ip link set veth1 up
sudo ip netns exec netns0 ip addr add 10.0.0.2/24 dev veth1
sudo ip netns exec netns0 ip route add default via 10.0.0.1 dev veth1
sudo ip netns exec netns0 ip link set dev lo up
sudo sysctl net.ipv4.ip_forward=1
sudo iptables -t nat -A POSTROUTING -o enp0s3 -j MASQUERADE
sudo echo "nameserver 8.8.8.8" > /etc/resolv.conf

